[mypy]
mypy_path = src
namespace_packages = True
explicit_package_bases = True
ignore_missing_imports = True
disallow_untyped_decorators = False
disable_error_code = misc, valid-type, attr-defined
warn_unused_ignores = False
exclude = migrations
